### ISSUE TITLE
Plans to build as a Dash component?

### ISSUE THREAD

**Issue by ndrezn** [pip-install-python/dash-full-calendar#1]
Wondering if you have plans to wrap this component using ~https://github.com/plotly/dash-component-in-notebook~ https://github.com/plotly/dash-component-boilerplate? Interesting strategy for the initial prototype!

**Comment by pip-install-python** [comment]
Hey @ndrezn, haven't used dash in the notebook much and haven't tested it but thats a good idea for down the road development. I know the component works in https://wasmdash.vercel.app/ .

**Comment by ndrezn** [comment]
Oops, wrong link! I meant to post: https://github.com/plotly/dash-component-boilerplate

This would allow you to use callbacks with this component.

**Comment by pip-install-python** [comment]
Yeah, its still in development but its an actual component at this point. Released it two days ago check out: https://community.plotly.com/t/pip-install-full-calendar-component/83460/7

and:
https://github.com/pip-install-python/full_calendar_component

**Comment by ndrezn** [comment]
Aha got it nice!
