### ISSUE TITLE
Feature Request: List-Week view also for List-Month

### ISSUE THREAD

**Issue by MauriceBrg** [pip-install-python/dash-full-calendar#2]
Hey,

I'm using your library to display upcoming training events and for some people they're relatively sparse, e.g. 1-2 events per month.

It would be great if it was possible to have the list view for greater timespans than a single week, e.g. a month or even a year.
We have big screens and the information density would be fine :)

Thanks for building this, made it really easy to add a calendar functionality to my internal app!

**Comment by pip-install-python** [comment]
Hey MauriceBrg,

Thanks for the kind words. Try setting initialView="dayGridYear" or  "multiMonthYear" that will give you a full years prospective. You can also roll back the release one prior if you'd like and have access to other options like resourceTimeline,
resourceTimeGridDay. I removed those as it was enterprise and when they where included you'd get a "license required" message. 

Outside of that, if you specifically want a list view it wouldn't be too complicated to create one yourself outside of this component. My recommendation would be to create a list view with dmc and connect callbacks to the full calendar. So on one side of the screen you have the calendar and on the other side you have a list of buttons or links of events and when you click on an event it uses callbacks and the props of full calendar to re-render the calendar as you want.

Check out the documentation: https://pip-install-python.com/pip/full_calendar_component
(need to update it a bit more) just been caught up in work and releasing a bunch of other components. but the documentation has some interesting use cases that you could build upon and a live view of ways you can change in between different initialView's and what that does or how to change the header.

**Comment by MauriceBrg** [comment]
Ah, I didn't realize this is built on top of https://fullcalendar.io/, that explains the available options :)

I thought it would be a relatively simple view to bolt on, but for external dependencies that's a different story...
Thanks for your recommendations, I found the documentation useful although it took me a while to find the source code for the other examples (only the first one is included directly on the page).

For now I'll stick to the weekly view and may build something custom if the need arises.
